config/routes.rb
Rails.application.routes.draw do
  resources :sites

  root to: 'sites#index'
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params[:site]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <title>AskKen</title>
  <!--%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true % -->
  <!--%= javascript_include_tag 'application', 'data-turbolinks-track' => true % -->
  <!--%= csrf_meta_tags %-->


    <link rel="stylesheet" href="/assets/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/normalize.min.css">
    <link rel="stylesheet" href="/assets/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/animate.css">
    <link rel="stylesheet" href="/assets/templatemo_misc.css">
    <link rel="stylesheet" href="/assets/templatemo_style.css">

    <script src="/assets/modernizr-2.6.2.min.js"></script>

  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet">


</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<%= render 'navbar' %>

<%= yield %>

<%= render 'footer' %>

<script src="/assets/jquery-1.10.1.min.js"></script>
<script>window.jQuery || document.write('<script src="/assets/jquery-1.10.1.min.js"><\/script>')</script>
<script src="/assets/jquery.easing-1.3.js"></script>
<script src="/assets/bootstrap.js"></script>
<script src="/assets/plugins.js"></script>
<script src="/assets/main.js"></script>


</body>

</html>

app/views/sites/_footer.html.erb
<div class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <span>Copyright &copy; 2014 <a href="#">Ask Ken Pte. Ltd. </a></span>
      </div> <!-- /.col-md-6 -->
      <div class="col-md-6 col-sm-6">
        <ul class="social">
          <li><a href="#" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-instagram"></a></li>
          <li><a href="#" class="fa fa-linkedin"></a></li>
          <li><a href="#" class="fa fa-rss"></a></li>
        </ul>
      </div> <!-- /.col-md-6 -->
    </div> <!-- /.row -->
  </div> <!-- /.container -->
</div> <!-- /.site-footer -->

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/_navbar.html.erb
<div id="front">
  <div class="site-header">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-6">
          <div id="templatemo_logo">
            <h1><a href="#" title="Ask Ken">Ask Ken</a></h1>
          </div> <!-- /.logo -->
        </div> <!-- /.col-md-4 -->
        <div class="col-md-8 col-sm-6 col-xs-6">
          <a href="#" class="toggle-menu"><i class="fa fa-bars"></i></a>
          <div class="main-menu">
            <ul>
              <li><a href="#front">Home</a></li>
              <li><a href="#services">Services</a></li>
              <li><a href="#products">Products</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div> <!-- /.main-menu -->
        </div> <!-- /.col-md-8 -->
      </div> <!-- /.row -->
      <div class="row">
        <div class="col-md-12">
          <div class="responsive">
            <div class="main-menu">
              <ul>
                <li><a href="#front">Home</a></li>
                <li><a href="#services">Services</a></li>
                <li><a href="#products">Products</a></li>
                <li><a href="#contact">Contact</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- /.container -->
  </div> <!-- /.site-header -->
</div> <!-- /#front -->

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>